FROM alpine:edge
RUN apk add --no-cache py3-pip git

COPY erso.sh /bin/erso
RUN chmod +x /bin/erso
ENTRYPOINT ["/bin/erso"]

ARG TARGET=main
RUN pip install git+https://github.com/urn/erso.git@$TARGET